name: Auto Sync Kaggle Notebooks

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight (UTC)
  workflow_dispatch:  # Allows manual triggering

jobs:
  update-kaggle:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Kaggle API
        run: pip install kaggle

      - name: Configure Kaggle API Key
        run: |
          mkdir -p ~/.kaggle
          echo "${{ secrets.KAGGLE_JSON }}" > ~/.kaggle/kaggle.json
          chmod 600 ~/.kaggle/kaggle.json

      - name: Read notebook list and download from Kaggle
        run: |
          while IFS= read -r notebook; do
            kaggle kernels pull "$notebook" -p .
          done < notebooks.txt

      - name: Commit and Push Changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Auto-update Kaggle notebooks" || echo "No changes to commit"
          git push origin main
